### ISSUE TITLE
Why is this package discontinued?

### ISSUE THREAD

**Issue by fprochazka** [nette/reflection#11]
It's really handy how it allows parsing "simple" annotations and helps resolve class imports.

**Comment by dg** [comment]
Look at the positive side: there will never appear BC break.

**Comment by JanTvrdik** [comment]
As far as I remember there was a plan to extract the simple annotation parser to another package (with refactored API) and possibly add few helper methods to nette/utils.

**Comment by dg** [comment]
Discontinued !== deprecated

**Comment by dg** [comment]
Few helper methods are now in https://github.com/nette/utils/blob/master/src/Utils/Reflection.php.

**Comment by enumag** [comment]
@dg About two years late but thanks anyway!

**Comment by Majkl578** [comment]
@milo: Sorry, but your action was rude and inappropriate (as long as you added the `<del>` only).

**Comment by milo** [comment]
@Majkl578 You right. @enumag Sorry if you feel offended, but term `thanks anyway` can express many states and in your sentences is the rude one.

If you want to continue in discussion, let's go to the forum, ping me here, and do not bother other developers.
